/* LOGIN */
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

/* CHECK-IN */
export const CHECKIN_LOADING = 'CHECKIN_LOADING';
export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILURE = 'GET_CUSTOMER_DETAILS_FAILURE';
export const CHECKIN_SUCCESS = 'CHECKIN_SUCCESS';
export const CHECKIN_FAILURE = 'CHECKIN_FAILURE';

/* CARE PLAN */
export const CARE_PLAN_LOADING = 'CARE_PLAN_LOADING';
export const GET_HEALTH_TIPS_SUCCESS = 'GET_HEALTH_TIPS_SUCCESS';
export const GET_HEALTH_TIPS_FAILURE = 'GET_HEALTH_TIPS_FAILURE';

/* DASHBOARD */
